openapi: 3.0.0
info:
  version: 1.0.0
  title: BoostTeams API docs
  description: BoostTeams의 API 문서입니다
  license:
    name: MIT
servers:
  - url: http://localhost:4000/
    description: BoostTeams Server
tags:
  - name: auth
    description: Join / Login / Logout
  - name: chat
    description: Chat Page
  - name: schedule
    description: Calendar Page
  - name: team
    description: Team Page
  - name: user
    description: User Manage
paths:
  # auth
  /api/auth/login:
    $ref: './paths/auth/login.yaml'
  /api/auth/github:
    $ref: './paths/auth/github.yaml'
  /api/auth/github/callback:
    $ref: './paths/auth/callback.yaml'
  /api/auth/signup:
    $ref: './paths/auth/signup.yaml'
  /api/auth/info:
    $ref: './paths/auth/info.yaml'
  # schdule
  /api/schedule/{team_id}:
    $ref: './paths/schedule/scheduleByTeamId.yaml'
  /api/schedule/{schedule_id}:
    $ref: './paths/schedule/scheduleByScheduleId.yaml'
  # chat
  /api/chat/room:
    $ref: './paths/chat/chat.yaml'
  /api/chat/room/{chatRoomId}:
    $ref: './paths/chat/chatRoom.yaml'
